Repository cipp00h/SSAP-IDE-BackEnd, pull requests merged in 2023-10, with the labels that each got.

#32 로그인 세션 인증 구현
  src/main/java/com/ssap/SSAPIDE/WebConfig.java
  src/main/java/com/ssap/SSAPIDE/controller/LoginController.java
  src/main/java/com/ssap/SSAPIDE/controller/SignupController.java
  src/main/java/com/ssap/SSAPIDE/interceptor/LogInterceptor.java
  src/main/java/com/ssap/SSAPIDE/interceptor/LoginCheckInterceptor.java
  src/main/java/com/ssap/SSAPIDE/session/SessionLoginConst.java
  src/test/java/com/ssap/SSAPIDE/service/ContainerServiceTest.java
Labels: 💡 기능

#34 사용자 조회 API 개발
  src/main/java/com/ssap/SSAPIDE/WebConfig.java
  src/main/java/com/ssap/SSAPIDE/controller/SignupController.java
  src/main/java/com/ssap/SSAPIDE/controller/UserController.java
  src/main/java/com/ssap/SSAPIDE/dto/CheckUserResponse.java
  src/main/java/com/ssap/SSAPIDE/interceptor/LogInterceptor.java
Labels: 💡 기능, :gear: 최적화

#35 사용자 조회 API 개발
  src/main/java/com/ssap/SSAPIDE/WebConfig.java
  src/main/java/com/ssap/SSAPIDE/controller/SignupController.java
  src/main/java/com/ssap/SSAPIDE/controller/UserController.java
  src/main/java/com/ssap/SSAPIDE/dto/CheckUserResponse.java
  src/main/java/com/ssap/SSAPIDE/interceptor/LogInterceptor.java
Labels: 💡 기능

#38 Test 코드 관련
  src/test/java/com/ssap/SSAPIDE/service/ContainerServiceTest.java
Labels: 🛠️리팩토링

#42 Web IDE내에서 파일 생성/삭제/수정 관련 기능 구현
  src/main/java/com/ssap/SSAPIDE/controller/FileController.java
  src/main/java/com/ssap/SSAPIDE/dto/FileRenameRequestDto.java
  src/main/java/com/ssap/SSAPIDE/model/FileAndFolder.java
  src/main/java/com/ssap/SSAPIDE/service/FileAndFolderService.java
Labels: 💡 기능

#45 컨테이너 생성시 member_id 값 DB에 저장되도록 수정 및 CORS 추가
  src/main/java/com/ssap/SSAPIDE/controller/ContainerController.java
  src/main/java/com/ssap/SSAPIDE/model/Container.java
  src/main/java/com/ssap/SSAPIDE/service/ContainerService.java
Labels: 💡 기능

#46 feature: CORS 처리 #44
  src/main/java/com/ssap/SSAPIDE/controller/ContainerController.java
  src/main/java/com/ssap/SSAPIDE/controller/FileController.java
  src/main/java/com/ssap/SSAPIDE/controller/FolderController.java
Labels: 💡 기능

#47 사용자별 컨테이너 조회
  src/main/java/com/ssap/SSAPIDE/WebConfig.java
  src/main/java/com/ssap/SSAPIDE/controller/LoginController.java
  src/main/java/com/ssap/SSAPIDE/controller/UserController.java
  src/main/java/com/ssap/SSAPIDE/domain/member/User.java
  src/main/java/com/ssap/SSAPIDE/dto/UserContainerResponse.java
  src/main/java/com/ssap/SSAPIDE/interceptor/LoginCheckInterceptor.java
  src/main/java/com/ssap/SSAPIDE/model/Container.java
  src/main/java/com/ssap/SSAPIDE/repository/ContainerRepository.java
  src/main/java/com/ssap/SSAPIDE/service/UserService.java
Labels: 💡 기능
